/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_project1;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author meghaumesha
 */
public class SignupFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignupFrame
     */
    public SignupFrame() {
        initComponents();
        
        phno_text.setVisible(false);
        
        hsup1_combo.setVisible(false);
        hsup2_combo.setVisible(false);
        auth1.setVisible(false);
        auth2.setVisible(false);
        
        hsup1_lb.setVisible(false);
        hsup2_lb.setVisible(false);
        auth1_lb.setVisible(false);
        auth2_lb.setVisible(false);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name_text = new javax.swing.JTextField();
        address_text = new javax.swing.JTextField();
        dob_text = new javax.swing.JTextField();
        gender_combo = new javax.swing.JComboBox<>();
        category_combo = new javax.swing.JComboBox<>();
        signup_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        phno_text = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        password_text = new javax.swing.JPasswordField();
        hsup1_lb = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        hsup2_lb = new javax.swing.JLabel();
        auth1_lb = new javax.swing.JLabel();
        auth1 = new javax.swing.JTextField();
        auth2_lb = new javax.swing.JLabel();
        auth2 = new javax.swing.JTextField();
        hsup1_combo = new javax.swing.JComboBox<>();
        hsup2_combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SIGN UP");

        jLabel2.setText("Name");

        jLabel3.setText("DOB");

        jLabel4.setText("Address");

        jLabel5.setText("Gender");

        jLabel6.setText("Category");

        name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_textActionPerformed(evt);
            }
        });

        gender_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        category_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Health Supporter", "Patient" }));
        category_combo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                category_comboFocusLost(evt);
            }
        });
        category_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_comboActionPerformed(evt);
            }
        });

        signup_button.setText("Sign up");
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });

        phno_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phno_textActionPerformed(evt);
            }
        });

        jLabel8.setText("Password");

        hsup1_lb.setText("Health Sup 1");

        hsup2_lb.setText("Health Sup 2");

        auth1_lb.setText("Auth Date");

        auth2_lb.setText("Auth Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(category_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password_text)
                            .addComponent(name_text)
                            .addComponent(dob_text)
                            .addComponent(address_text)
                            .addComponent(phno_text))
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gender_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hsup1_lb)
                            .addComponent(auth1_lb))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(auth1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hsup1_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hsup2_lb)
                            .addComponent(auth2_lb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(auth2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hsup2_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(signup_button)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dob_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(address_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(phno_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(gender_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(category_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hsup1_lb)
                    .addComponent(hsup2_lb)
                    .addComponent(hsup1_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hsup2_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auth1_lb)
                    .addComponent(auth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auth2_lb)
                    .addComponent(auth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(signup_button)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_textActionPerformed

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        Connection con = null;
        try {
            // TODO add your handling code here:
            this.setVisible(false);
            dispose();
            String categ = (String) category_combo.getSelectedItem();
            con = DBMS_Connection.get();
            CallableStatement stmt = con.prepareCall("{ call proc_signup_insert(?,?,?,?,?,?,?,?,?,?,?)}");
            stmt.registerOutParameter(11, Types.VARCHAR);
            
            stmt.setString(1,dob_text.getText());
            stmt.setString(2,name_text.getText());
            stmt.setString(3,address_text.getText());
            stmt.setString(4,(String)gender_combo.getSelectedItem());
            stmt.setString(5,password_text.getText());
           
            if(categ.equalsIgnoreCase("patient")){
                stmt.setString(10, "patient");
                String hsup1 = (String)hsup1_combo.getSelectedItem();
                if(!hsup1.equals(""))
                    stmt.setString(6, hsup1);
                else
                    stmt.setString(6, null);
                stmt.setString(7, auth1.getText());

                String hsup2 = (String)hsup2_combo.getSelectedItem();
                if(!hsup2.equals(""))
                    stmt.setString(8, hsup2);
                else
                    stmt.setString(8, null);
                stmt.setString(9, auth2.getText());
            }else{
                stmt.setString(6, null);
                stmt.setString(7, null);
                stmt.setString(8, null);
                stmt.setString(9, null);
                stmt.setString(10, "health supporter");
            }
            
            stmt.execute();
            String generatedId = stmt.getString(11);
            dispose();
            DBMS_Connection.loginID = generatedId;
            System.out.print(generatedId);
//            LoginFrame lf = new LoginFrame();
//            lf.setVisible(true);

            if(categ.equalsIgnoreCase("patient")){
                DBMS_Connection.patientType = "well";
                Patient_Menu pm = new Patient_Menu();
                pm.setVisible(true);
            }else{
                HealthSupMainFrame hsmf = new HealthSupMainFrame();
                hsmf.setVisible(true);
            }
            JOptionPane.showMessageDialog(this, "Signup successful. Your login ID is "+DBMS_Connection.loginID);
                
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(SignupFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(SignupFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_signup_buttonActionPerformed

    private void phno_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phno_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phno_textActionPerformed

    private void category_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_comboActionPerformed

        
    }//GEN-LAST:event_category_comboActionPerformed

    private void category_comboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_category_comboFocusLost
        // TODO add your handling code here:
        String categ = (String) category_combo.getSelectedItem();
        if(categ.equalsIgnoreCase("patient")){
            try {
                Connection con = DBMS_Connection.get();
                String sql = "Select id from health_supporter";
                PreparedStatement stmt = con.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery(sql);
                
                hsup1_combo.removeAllItems();
                hsup2_combo.removeAllItems();
                
                hsup1_combo.addItem("");
                hsup2_combo.addItem("");
                while(rs.next()){
                    hsup1_combo.addItem(rs.getString("id"));
                    hsup2_combo.addItem(rs.getString("id"));
                }
                hsup1_combo.setVisible(true);
                hsup2_combo.setVisible(true);
                auth1.setVisible(true);
                auth2.setVisible(true);
                
                hsup1_lb.setVisible(true);
                hsup2_lb.setVisible(true);
                auth1_lb.setVisible(true);
                auth2_lb.setVisible(true);
                pack();
            } catch (SQLException ex) {
                Logger.getLogger(SignupFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (categ.equalsIgnoreCase("health supporter")){
            hsup1_combo.setVisible(false);
            hsup2_combo.setVisible(false);
            auth1.setVisible(false);
            auth2.setVisible(false);

            hsup1_lb.setVisible(false);
            hsup2_lb.setVisible(false);
            auth1_lb.setVisible(false);
            auth2_lb.setVisible(false);
            pack();
        }
    }//GEN-LAST:event_category_comboFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_text;
    private javax.swing.JTextField auth1;
    private javax.swing.JLabel auth1_lb;
    private javax.swing.JTextField auth2;
    private javax.swing.JLabel auth2_lb;
    private javax.swing.JComboBox<String> category_combo;
    private javax.swing.JTextField dob_text;
    private javax.swing.JComboBox<String> gender_combo;
    private javax.swing.JComboBox<String> hsup1_combo;
    private javax.swing.JLabel hsup1_lb;
    private javax.swing.JComboBox<String> hsup2_combo;
    private javax.swing.JLabel hsup2_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField name_text;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JTextField phno_text;
    private javax.swing.JButton signup_button;
    // End of variables declaration//GEN-END:variables
}
